Freeze ideascube installation
I got the following issue after upgrading, it needs to be investigated

Wed May 31 19:56:18 2017 - *** Starting uWSGI 2.0.7-debian (32bit) on
[Wed May 31 19:56:17 2017] ***
Wed May 31 19:56:18 2017 - compiled with version: 4.9.2 on 26 February
2017 03:25:27
Wed May 31 19:56:18 2017 - os: Linux-4.8.4-sunxi #6 SMP Sun Oct 23
15:55:47 CEST 2016
Wed May 31 19:56:18 2017 - nodename: captivportal-97
Wed May 31 19:56:18 2017 - machine: armv7l
Wed May 31 19:56:18 2017 - clock source: unix
Wed May 31 19:56:18 2017 - pcre jit disabled
Wed May 31 19:56:18 2017 - detected number of CPU cores: 2
Wed May 31 19:56:18 2017 - current working directory: /
Wed May 31 19:56:18 2017 - writing pidfile to
/run/uwsgi/app/ideascube/pid
Wed May 31 19:56:18 2017 - detected binary path: /usr/bin/uwsgi-core
Wed May 31 19:56:18 2017 - *** dumping internal routing table ***
Wed May 31 19:56:18 2017 - [rule: 0] subject: ${cookie[sessionid]} func:
empty action: goto:cacheme
Wed May 31 19:56:18 2017 - [rule: 1] action: continue:
Wed May 31 19:56:18 2017 - [rule: 2] label: cacheme
Wed May 31 19:56:18 2017 - [rule: 3] subject: path_info regexp:
^/[a-z]{2}/$ action: cache:key=${REQUEST_URI},name=ideascube
Wed May 31 19:56:18 2017 - [rule: 4] subject: path_info regexp:
^/[a-z]{2}/$ action:
cachestore:key=${REQUEST_URI},name=ideascube,expires=300
Wed May 31 19:56:18 2017 - [rule: 5] subject: path_info regexp:
^/[a-z]{2}/blog/$ action: cache:key=${REQUEST_URI},name=ideascube
Wed May 31 19:56:18 2017 - [rule: 6] subject: path_info regexp:
^/[a-z]{2}/blog/$ action:
cachestore:key=${REQUEST_URI},name=ideascube,expires=300
Wed May 31 19:56:18 2017 - [rule: 7] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/\?source=(.*)$ action:
cache:key=${REQUEST_URI},name=ideascube
Wed May 31 19:56:18 2017 - [rule: 8] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/\?source=(.*)$ action:
cachestore:key=${REQUEST_URI},name=ideascube,expires=300
Wed May 31 19:56:18 2017 - [rule: 9] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/\?page=\d$ action:
cache:key=${REQUEST_URI},name=ideascube
Wed May 31 19:56:18 2017 - [rule: 10] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/\?page=\d$ action:
cachestore:key=${REQUEST_URI},name=ideascube,expires=300
Wed May 31 19:56:18 2017 - [rule: 11] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/$ action: cache:key=${REQUEST_URI},name=ideascube
Wed May 31 19:56:18 2017 - [rule: 12] subject: request_uri regexp:
^/[a-z]{2}/mediacenter/$ action:
cachestore:key=${REQUEST_URI},name=ideascube,expires=300
Wed May 31 19:56:18 2017 - *** end of the internal routing table ***
Wed May 31 19:56:18 2017 - setgid() to 1000
Wed May 31 19:56:18 2017 - set additional group 27 (sudo)
Wed May 31 19:56:18 2017 - set additional group 33 (www-data)
Wed May 31 19:56:18 2017 - setuid() to 1000
Wed May 31 19:56:18 2017 - your processes number limit is 7836
Wed May 31 19:56:18 2017 - your memory page size is 4096 bytes
Wed May 31 19:56:18 2017 - detected max file descriptor number: 1024
Wed May 31 19:56:18 2017 - lock engine: pthread robust mutexes
Wed May 31 19:56:18 2017 - thunder lock: disabled (you can enable it
with --thunder-lock)
Wed May 31 19:56:18 2017 - *** Cache "ideascube" initialized: 6MB (key:
2136 bytes, keys: 213600 bytes, data: 6553600 bytes, bitmap: 0 bytes)
preallocated ***
Wed May 31 19:56:18 2017 - uwsgi socket 0 bound to UNIX address
/run/uwsgi/app/ideascube/socket fd 7
Wed May 31 19:56:18 2017 - uwsgi socket 1 bound to UNIX address
/tmp/ideascube.sock fd 8
Wed May 31 19:56:18 2017 - Python version: 2.7.9 (default, Aug 13 2016,
18:15:29)  [GCC 4.9.2]
Wed May 31 19:56:18 2017 - Set PythonHome to /opt/venvs/ideascube/
ImportError: No module named site